version: "3"

services:
  k-cse-diy-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: k-cse-diy-server
    restart: always
    environment:
      - SPRING_PORT=${SPRING_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DIY_ADMIN_USERNAME=${DIY_ADMIN_USERNAME}
      - DIY_ADMIN_PASSWORD=${DIY_ADMIN_PASSWORD}
    depends_on:
      - k-cse-diy-database
    expose:
      - ${SPRING_PORT}
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    networks:
      - k-cse-diy-network

  k-cse-diy-database:
    image: mysql:8.0
    restart: always
    container_name: k-cse-diy-database
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "52002:3306"
    volumes:
      - k-cse-diy-database:/var/lib/mysql
    networks:
      - k-cse-diy-network

volumes:
  k-cse-diy-database:

networks:
  k-cse-diy-network:
    driver: bridge
